/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import com.sun.awt.AWTUtilities;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 *
 * @author ariellugo92
 */
public class InicioSplash extends javax.swing.JFrame {

    /**
     * Creates new form InicioSplash
     */
    
    private InicioSplash barraProgresoFrame = this;
    
    public InicioSplash() {
        initComponents();
        if (barraProgresoFrame.getJProgressBar().getValue() == 60) {
            AWTUtilities.setWindowOpacity(this, Float.valueOf(0.5f));
        }
        inicioHilo();
    }

    private void inicioHilo(){
    
        Thread hilo = new Thread(new Runnable() {

            @Override
            public void run() {
                LoginDeInicio login = new LoginDeInicio(barraProgresoFrame);
                login.setVisible(true);
                dispose();
            }
        });
        hilo.start();
    }
    
    public JProgressBar getJProgressBar(){
        return barraDeProgreso;
    }
    
    public JLabel getJLabel(){
        return LabelProgreso;
    }
    
    public void desvanecer(){
        if (barraDeProgreso.getValue() == 60) {
            AWTUtilities.setWindowOpacity(this, Float.valueOf(0.5f));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeProgreso = new javax.swing.JProgressBar();
        LabelProgreso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Iconos/iconoPrin.png")).getImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraDeProgreso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barraDeProgreso.setStringPainted(true);
        getContentPane().add(barraDeProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 560, -1));

        LabelProgreso.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(LabelProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 240, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/ajax-loader.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 70, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/fondoTecnologico.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSplash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelProgreso;
    private javax.swing.JProgressBar barraDeProgreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
