/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author IaraDenisse
 */
public class Prueba extends javax.swing.JDialog {

    /**
     * Creates new form Prueba
     */
    public Prueba(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoEmp_Modicando = new javax.swing.JTextField();
        txtCelularEmp_Modicando = new javax.swing.JTextField();
        txtNombreEmp_Modicando = new javax.swing.JTextField();
        txtTelefonoEmp_Modicando = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        itemHombreElegidoEmp_Modicando = new javax.swing.JRadioButton();
        itemMujerElegidoEmp_Modicando = new javax.swing.JRadioButton();
        jXFormattedTextField2 = new org.jdesktop.swingx.JXFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        labelFotoEmp = new javax.swing.JLabel();
        botonElegirFotoModificando = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSalarioEmp_Modicando = new javax.swing.JTextField();
        botonActualizarTabla = new org.edisoncor.gui.button.ButtonTask();
        jComboBox1 = new javax.swing.JComboBox();
        jXFormattedTextField1 = new org.jdesktop.swingx.JXFormattedTextField();
        botonLimpiarModifica = new org.edisoncor.gui.button.ButtonTask();
        botonModificarEmp = new org.edisoncor.gui.button.ButtonTask();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTask1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/EditarEmpleado.png"))); // NOI18N
        labelTask1.setText("Editar Empleados");
        labelTask1.setDescription("Por favor!, Elija en la tabla el empleado que va a modificar");
        jPanel6.add(labelTask1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 520, 60));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("    Edite los campos a modificar, una vez realizado los cambios seleccione el boton de modificar y siga las istrucciones");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 660, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Apellido");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 75, 25));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Sexo");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 75, 25));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 75, 25));

        txtApellidoEmp_Modicando.setToolTipText("Agregue un apellido al empleado");
        jPanel3.add(txtApellidoEmp_Modicando, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 150, 25));

        txtCelularEmp_Modicando.setToolTipText("Celular movil");
        jPanel3.add(txtCelularEmp_Modicando, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 150, 25));

        txtNombreEmp_Modicando.setToolTipText("Agregue un nombre al empleado");
        jPanel3.add(txtNombreEmp_Modicando, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 150, 25));

        txtTelefonoEmp_Modicando.setToolTipText("Telefono convencional");
        jPanel3.add(txtTelefonoEmp_Modicando, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 150, 25));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Celular");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 75, 25));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Cedula");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 75, 25));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Telefono");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 75, 25));

        itemHombreElegidoEmp_Modicando.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        itemHombreElegidoEmp_Modicando.setText("Hombre");
        jPanel3.add(itemHombreElegidoEmp_Modicando, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        itemMujerElegidoEmp_Modicando.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        itemMujerElegidoEmp_Modicando.setText("Mujer");
        jPanel3.add(itemMujerElegidoEmp_Modicando, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jXFormattedTextField2.setText("jXFormattedTextField2");
        jPanel3.add(jXFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 520, 160));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFotoEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/fotoEmp.png"))); // NOI18N
        labelFotoEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(labelFotoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 150));

        botonElegirFotoModificando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/subirPic.png"))); // NOI18N
        botonElegirFotoModificando.setText(" Elegir Foto");
        jPanel5.add(botonElegirFotoModificando, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/camara.png"))); // NOI18N
        jButton2.setText(" Tomar Foto");
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 240, 220));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Laborales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Fecha de ingreso");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 25));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Salario");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 75, 25));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Departamento");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 25));

        txtSalarioEmp_Modicando.setToolTipText("Ingrese el salario en moneda nacional");
        jPanel4.add(txtSalarioEmp_Modicando, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 25));

        botonActualizarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/Modificar.png"))); // NOI18N
        botonActualizarTabla.setText("Actualizar");
        botonActualizarTabla.setDescription("Tabla");
        jPanel4.add(botonActualizarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 170, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jXFormattedTextField1.setText("jXFormattedTextField1");
        jPanel4.add(jXFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 520, 150));

        botonLimpiarModifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/limpiarBoton.png"))); // NOI18N
        botonLimpiarModifica.setText("Limpiar");
        botonLimpiarModifica.setDescription("Ventanas");
        jPanel6.add(botonLimpiarModifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 140, -1));

        botonModificarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/EmpModificado.png"))); // NOI18N
        botonModificarEmp.setText("Modificar");
        botonModificarEmp.setDescription("Empleados");
        jPanel6.add(botonModificarEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 150, -1));

        jScrollPane2.setViewportView(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Prueba dialog = new Prueba(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask botonActualizarTabla;
    private javax.swing.JButton botonElegirFotoModificando;
    private org.edisoncor.gui.button.ButtonTask botonLimpiarModifica;
    private org.edisoncor.gui.button.ButtonTask botonModificarEmp;
    private javax.swing.JRadioButton itemHombreElegidoEmp_Modicando;
    private javax.swing.JRadioButton itemMujerElegidoEmp_Modicando;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXFormattedTextField jXFormattedTextField1;
    private org.jdesktop.swingx.JXFormattedTextField jXFormattedTextField2;
    private javax.swing.JLabel labelFotoEmp;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private javax.swing.JTextField txtApellidoEmp_Modicando;
    private javax.swing.JTextField txtCelularEmp_Modicando;
    private javax.swing.JTextField txtNombreEmp_Modicando;
    private javax.swing.JTextField txtSalarioEmp_Modicando;
    private javax.swing.JTextField txtTelefonoEmp_Modicando;
    // End of variables declaration//GEN-END:variables
}
