/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Archivos.ArchivoDepartamentos;
import Pojos.Cuentas;
import Pojos.Departamentos;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ariellugo92
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private LoginDeInicio GifProgreso;
    String user = LoginDeInicio.getUsuario().trim();
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        this.setExtendedState(VentanaPrincipal.MAXIMIZED_BOTH); 
        LoginDeInicio login = new LoginDeInicio();
    }

    VentanaPrincipal(LoginDeInicio GifProgreso) {
        this.GifProgreso = GifProgreso;
        setProgreso();
        GifProgreso.getJBusy().setVisible(false);
        initComponents();
//        txtLogeado.setText(user);
//        btnUser.setText(user);
        labelLogeo.setText("Bienvenido sr@ " + user + ", por favor elija una opcion.");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }
    
    private void setProgreso(){
          GifProgreso.getJBusy();
        try {
            Thread.sleep(1500);
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(null, "HUBO UN ERROR AL EJECUTAR LA APLICACION");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrin = new jcMousePanel.jcMousePanel();
        jPanel1 = new javax.swing.JPanel();
        btonDptos = new javax.swing.JButton();
        botonProductos = new javax.swing.JButton();
        botonVentas = new javax.swing.JButton();
        botonEmpleados = new javax.swing.JButton();
        botonCompras = new javax.swing.JButton();
        botonRRHH = new javax.swing.JButton();
        labelLogeo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        menuUser_Ver = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuUser_Editar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuUser_Cerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Iconos/iconoPrin.png")).getImage());
        setPreferredSize(null);

        panelPrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/fondoPrincipal.jpeg"))); // NOI18N
        panelPrin.setVisibleLogo(false);
        panelPrin.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btonDptos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/1425016208_companies.png"))); // NOI18N
        btonDptos.setText(" Gestionar departamentos");
        btonDptos.setBorder(null);
        btonDptos.setPreferredSize(new java.awt.Dimension(170, 70));
        btonDptos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/1425016208_companies_precionado.png"))); // NOI18N
        btonDptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonDptosActionPerformed(evt);
            }
        });
        jPanel1.add(btonDptos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 250, 80));

        botonProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/productos.png"))); // NOI18N
        botonProductos.setText(" Gestionar productos");
        botonProductos.setBorder(null);
        botonProductos.setBorderPainted(false);
        botonProductos.setPreferredSize(new java.awt.Dimension(170, 70));
        botonProductos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/productos_precionado.png"))); // NOI18N
        botonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProductosActionPerformed(evt);
            }
        });
        jPanel1.add(botonProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 250, 80));

        botonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/ventas.png"))); // NOI18N
        botonVentas.setText(" Gestionar Ventas");
        botonVentas.setBorder(null);
        botonVentas.setPreferredSize(new java.awt.Dimension(170, 70));
        botonVentas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/ventas_precionado.png"))); // NOI18N
        jPanel1.add(botonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 250, 80));

        botonEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/empleados.png"))); // NOI18N
        botonEmpleados.setText(" Gestionar empleados");
        botonEmpleados.setBorder(null);
        botonEmpleados.setBorderPainted(false);
        botonEmpleados.setPreferredSize(new java.awt.Dimension(170, 70));
        botonEmpleados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/empleados_precionado.png"))); // NOI18N
        botonEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(botonEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 250, 80));

        botonCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/agregar cmpras.png"))); // NOI18N
        botonCompras.setText("Gestionar Compras");
        botonCompras.setBorder(null);
        botonCompras.setPreferredSize(new java.awt.Dimension(170, 70));
        botonCompras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/agregar cmpras_precionado.png"))); // NOI18N
        jPanel1.add(botonCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 250, 80));

        botonRRHH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/rrhh.png"))); // NOI18N
        botonRRHH.setText("Recursos humanos");
        botonRRHH.setBorder(null);
        botonRRHH.setPreferredSize(new java.awt.Dimension(170, 70));
        botonRRHH.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/rrhh_precionado.png"))); // NOI18N
        jPanel1.add(botonRRHH, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 250, 80));

        labelLogeo.setText("jLabel1");
        jPanel1.add(labelLogeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 290, 30));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(100, 220, 3, 205);
        panelPrin.add(jPanel1, gridBagConstraints);

        getContentPane().add(panelPrin, java.awt.BorderLayout.CENTER);

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/userMenu.png"))); // NOI18N
        menuUsuario.setText("Usuarios");
        menuUsuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        menuUser_Ver.setText("Ver usuarios");
        menuUsuario.add(menuUser_Ver);
        menuUsuario.add(jSeparator1);

        menuUser_Editar.setText("Editar usuarios");
        menuUsuario.add(menuUser_Editar);
        menuUsuario.add(jSeparator2);

        menuUser_Cerrar.setText("Cerrar sesion");
        menuUser_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUser_CerrarActionPerformed(evt);
            }
        });
        menuUsuario.add(menuUser_Cerrar);

        jMenuBar1.add(menuUsuario);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 1041, 553);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpleadosActionPerformed
        try {
            ArchivoDepartamentos ddao = new ArchivoDepartamentos();
            List<Departamentos> dpto = ddao.encontrar();
            
            if (dpto.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Primero introduzca departmaentos para ubicar a sus empleados");
                return;
            }
            
            GestionarEmpleados dialog = new GestionarEmpleados(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonEmpleadosActionPerformed

    private void botonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductosActionPerformed
        GestionarProductos dialog = new GestionarProductos(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_botonProductosActionPerformed

    private void btonDptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonDptosActionPerformed
        GestionarDptos dialog = new GestionarDptos(new javax.swing.JFrame(), true);
        if (LoginDeInicio.getTipos().equals("Administrador")) {
            dialog.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Lo sentimos necesita permisos de administrador para acceder "
                    + "a esta opcion", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btonDptosActionPerformed

    private void menuUser_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUser_CerrarActionPerformed
        new LoginDeInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuUser_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCompras;
    private javax.swing.JButton botonEmpleados;
    private javax.swing.JButton botonProductos;
    private javax.swing.JButton botonRRHH;
    private javax.swing.JButton botonVentas;
    private javax.swing.JButton btonDptos;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel labelLogeo;
    private javax.swing.JMenuItem menuUser_Cerrar;
    private javax.swing.JMenuItem menuUser_Editar;
    private javax.swing.JMenuItem menuUser_Ver;
    private javax.swing.JMenu menuUsuario;
    private jcMousePanel.jcMousePanel panelPrin;
    // End of variables declaration//GEN-END:variables
}